### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by TianheWu** [anse3832/IQT#2]
Using GPU 2
number of train scenes: 160
number of test scenes: 40
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1875/1875 [06:53<00:00,  4.54it/s]
Traceback (most recent call last):
  File "/home/wth/IQT/train.py", line 156, in <module>
    loss, rho_s, rho_p = train_epoch(config, epoch, model_transformer, model_backbone, save_output, criterion, optimizer, scheduler, train_loader)
  File "/home/wth/IQT/trainer.py", line 87, in train_epoch
    rho_p, _ = pearsonr(np.squeeze(pred_epoch), np.squeeze(labels_epoch))
  File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/stats/stats.py", line 4045, in pearsonr
    normxm = linalg.norm(xm)
  File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/linalg/misc.py", line 145, in norm
    a = np.asarray_chkfinite(a)
  File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs

I using scipy 1.7.2. I don't know how to solve this problem.

**Comment by anse3832** [comment]
Maybe the variable "pred_epoch" has infs or NaNs when calculating correlation coefficients. Did you check for that?

**Comment by 870715478** [comment]
> Using GPU 2 number of train scenes: 160 number of test scenes: 40 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1875/1875 [06:53<00:00, 4.54it/s] Traceback (most recent call last): File "/home/wth/IQT/train.py", line 156, in loss, rho_s, rho_p = train_epoch(config, epoch, model_transformer, model_backbone, save_output, criterion, optimizer, scheduler, train_loader) File "/home/wth/IQT/trainer.py", line 87, in train_epoch rho_p, _ = pearsonr(np.squeeze(pred_epoch), np.squeeze(labels_epoch)) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/stats/stats.py", line 4045, in pearsonr normxm = linalg.norm(xm) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/linalg/misc.py", line 145, in norm a = np.asarray_chkfinite(a) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite raise ValueError( ValueError: array must not contain infs or NaNs
> 
> I using scipy 1.7.2. I don't know how to solve this problem.

Can datasets be used directly? Need to deal with it? Like the format or something?

**Comment by TianheWu** [comment]
I solved this problem by redownload the pre-trained model.

---Original---
From: ***@***.***&gt;
Date: Tue, Jan 4, 2022 20:55 PM
To: ***@***.***&gt;;
Cc: "Tianhe ***@***.******@***.***&gt;;
Subject: Re: [anse3832/IQT] ValueError: array must not contain infs or NaNs (Issue #2)




  
Using GPU 2 number of train scenes: 160 number of test scenes: 40 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1875/1875 [06:53<00:00, 4.54it/s] Traceback (most recent call last): File "/home/wth/IQT/train.py", line 156, in loss, rho_s, rho_p = train_epoch(config, epoch, model_transformer, model_backbone, save_output, criterion, optimizer, scheduler, train_loader) File "/home/wth/IQT/trainer.py", line 87, in train_epoch rho_p, _ = pearsonr(np.squeeze(pred_epoch), np.squeeze(labels_epoch)) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/stats/stats.py", line 4045, in pearsonr normxm = linalg.norm(xm) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/scipy/linalg/misc.py", line 145, in norm a = np.asarray_chkfinite(a) File "/home/wth/anaconda3/envs/wthEnv/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite raise ValueError( ValueError: array must not contain infs or NaNs
 
I using scipy 1.7.2. I don't know how to solve this problem.
  
Can datasets be used directly? Need to deal with it? Like the format or something?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
